name: Build wheels (on-demand)

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]
        python-version: ['3.10', '3.9', '3.8', '3.7']
        compiler: ['gcc']
        architecture: ['x86', 'x64']

    steps:
      - uses: actions/checkout@v3

      # Setup for Windows - installs the correct python architecture, x86 / x64
      - name: Set up Python (Win) ${{ matrix.python-version }} ${{ matrix.architecture }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
        if: runner.os == 'Windows'

      # Setup for Mac & Linux, both don't support architecture selection without using specific versions
      - name: Set up Python (Non-Win) ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
        if: runner.os != 'Windows'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.3

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
          python -m cibuildwheel --output-dir wheelhouse ./hwdecrypt_src

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
